FULL_RUN =0
TEST_RUN =1



#Generic Execution Status
EXT_REP_SUCCESS=0
EXT_REP_FAILURE=1


EXTENSION_DOWNLOAD_SUCCESS=1

# All Param Store Errors will start from 1000
EXT_REP_SVR_ERROR_PARAM_STORE = 1000


#All Crawling related Errors will start from 2000
EXT_REP_CRAWL_ERROR= 2000

#All URL fetch related Errors will start from 3000
EXT_REP_URL_FETCH_ERROR= 3000

#All download Extension related Errors will start from 4000
EXT_REP_DOWNLOAD_EXTENSION_ERROR= 4000 

# All step function execution related Errors will start from 5000
EXT_REP_INVOKE_STEP_FUNCTION_ERROR= 5000

# All Secret Manager related Errors will start from 6000
EXT_REP_SVR_ERROR_SECRET_MANAGER = 6000

# All GTI Anlysis Related Errors will start from 7000
EXT_REP_GTI_ANALYSIS_INVALID_SOURCE_PATH = 7000
EXT_REP_GTI_ANALYSIS_NOT_NEEDED = 7001
EXT_REP_GTI_ANALYSIS_FAILED_TO_GET_SOURCE_FROM_S3 = 7002
EXT_REP_GTI_ANALYSIS_FAILED_TO_GET_FILELIST = 7003
EXT_REP_GTI_ANALYSIS_FAILED_TO_GET_URLSLIST = 7004
EXT_REP_GTI_ANALYSIS_FAILED_TO_CREATE_FINAL_GTI_RESPONSE = 7005
EXT_REP_GTI_ANALYSIS_FAILED_TO_GET_GTI_RESPONSE = 7006
EXT_REP_GTI_ANALYSIS_FAILED_TO_UPDATE_DATA_IN_BASE_INFO_DB = 7007


# All Source code Analysis Related Errors will start from 8000
EXT_REP_SOURCE_CODE_ANALYZER_INVALID_SOURCE_PATH = 8000
EXT_REP_SOURCE_CODE_ANALYZER_FAILED_TO_GET_FILELIST = 8001
EXT_REP_SOURCE_CODE_ANALYZER_FAILED_TO_GET_SOURCE_FROM_S3 = 8002
EXT_REP_SOURCE_CODE_ANALYZER_FAILED_TO_UPDATE_DATA_IN_BASE_INFO_DB_FOR_DNG_API = 8003
EXT_REP_SOURCE_CODE_ANALYZER_FAILED_TO_UPDATE_DATA_IN_BASE_INFO_DB_FOR_STRIDE = 8004
EXT_REP_SOURCE_CODE_ANALYZER_EITHER_DANG_API_OR_STRIDE_COMPONENT_FAILED = 8005
EXT_REP_SOURCE_CODE_ANALYZER_DANG_API_ANALYSIS_FAILED = 8006
EXT_REP_SOURCE_CODE_ANALYZER_STRIDE_ANALYSIS_FAILED = 8007

# DB field Names
EXT_REP_BASE_INFO_GTI_ANALYSIS_FIELD = "GtiAnalysisData"
EXT_REP_BASE_INFO_MANIFEST_FIELD = "manifest"
EXT_REP_BASE_INFO_DANGEROUS_API_FIELD = "DangerousAPIData"
EXT_REP_BASE_INFO_API_DATA_FOR_STRIDE_FIELD = "APIDataForSTRIDE"

#Http Return Success Code
EXT_REP_HTTP_OK = 200

#Http Return Success Code
EXT_REP_HTTP_SERVER_ERROR = 500

# 
EXT_REP_HTTP_PAGE_NOT_FOUND = 404
